mlflow:
  experiment_name: "metro_preprocessing"
  experiment_id: 1
  run_name: "preprocessing_v2"
  tracking_uri: "http://127.0.0.1:8080"

data:
  input:
    path: "../data/raw.csv"
    delimiter: ","
    encoding: "utf-8"
    columns:
      message_id: "message_id"
      text: "text"
      date: "date"
      views: "views"
      reactions: "reactions"
      comments: "comments"
      channel_name: "channel_name"
      word_count: "word_count"
  
  output:
    path: "../data/data_processed2.csv"
    save_processed: true
    include_original: false

preprocessing:
  stage1:
    remove_emojis: true
    find_stations: true
    remove_stopwords: true
    min_words: 5
    max_words: 150
    min_date: "2020-01-01"

  stage2:
    library: "pymorphy3"
    batch_processing: true
    custom_stopwords: true
    batch_size: 100
    min_word_length: 3
  
  stations: [
    "сокольники", "красносельская", "комсомольская", "красные ворота",
    "чистые пруды", "лубянка", "охотный ряд", "библиотека им. ленина",
    "кропоткинская", "парк культуры", "фрунзенская", "спортивная",
    "воробьёвы горы", "университет", "проспект вернадского", "юго-западная",
    "тропарёво", "алма-атинская", "красногвардейская", "домодедовская",
    "орехово", "царицыно", "кантемировская", "каширская", "коломенская",
    "автозаводская", "павелецкая", "новокузнецкая", "театральная",
    "тверская", "маяковская", "белорусская", "динамо", "аэропорт",
    "сокол", "войковская", "водный стадион", "речной вокзал",
    "пятницкое шоссе", "митино", "волоколамская", "мякинино", "строгино",
    "крылатское", "молодежная", "кунцевская", "славянский бульвар",
    "парк победы", "киевская", "смоленская", "арбатская",
    "площадь революции", "курская", "бауманская", "электрозаводская",
    "семеновская", "партизанская", "измайловская", "первомайская",
    "щелковская", "александровский сад", "выставочная", "международная",
    "студенческая", "кутузовская", "фили", "багратионовская",
    "филевский парк", "пионерская", "новослободская", "проспект мира",
    "таганская", "добрынинская", "октябрьская", "краснопресненская",
    "медведково", "бабушкинская", "свиблово", "ботанический сад",
    "вднх", "алексеевская", "рижская", "сухаревская", "тургеневская",
    "китай-город", "третьяковская", "шаболовская", "ленинский проспект",
    "академическая", "профсоюзная", "новые черемушки", "калужская",
    "беляево", "коньково", "теплый стан", "ясенево", "новоясеневская",
    "жулебино", "лермонтовский проспект", "выхино", "рязанский проспект",
    "кузьминки", "текстильщики", "волгоградский проспект", "пролетарская",
    "кузнецкий мост", "пушкинская", "баррикадная", "улица 1905 года",
    "беговая", "полежаевская", "октябрьское поле", "щукинская", "спартак",
    "тушинская", "сходненская", "планерная", "новокосино", "новогиреево",
    "перово", "шоссе энтузиастов", "авиамоторная", "площадь ильича",
    "марксистская", "деловой центр", "алтуфьево", "бибирево", "отрадное",
    "владыкино", "петровско-разумовская", "тимирязевская", "дмитровская",
    "савеловская", "менделеевская", "цветной бульвар", "чеховская",
    "боровицкая", "полянка", "серпуховская", "тульская", "нагатинская",
    "нагорная", "нахимовский проспект", "севастопольская", "чертановская",
    "южная", "пражская", "улица академика янгеля", "аннино",
    "бульвар дмитрия донского", "марьина роща", "достоевская", "трубная",
    "сретенский бульвар", "чкаловская", "римская", "крестьянская застава",
    "дубровка", "кожуховская", "печатники", "волжская", "люблино",
    "братиславская", "марьино", "борисово", "шипиловская", "зябликово",
    "варшавская", "каховская", "битцевский парк", "лесопарковая",
    "улица старо-качаловская", "улица скобелевская",
    "бульвар адмирала ушакова", "улица горчакова", "бунинская аллея",
    "лухмановская", "улица дмитриевского", "косино", "юго-восточная",
    "окская", "стахановская", "нижегородская", "коммунарка",
    "корниловская", "тютчевская", "генерала тюленева",
    "университет дружбы народов", "новаторская", "вавиловская",
    "крымская", "зил", "метро"
  ]
  
  metro_stopwords: [
    "метро", "станция", "пассажир", "москва", "московский",
    "подземка", "время", "город", "работа", "транспорт",
    "это", "который", "также", "год", "день", "новый", "vk"
  ]