mlflow:
  experiment_name: "metro_preprocessing"
  experiment_id: 1
  run_name: "extra_stopwords_removal"
  tracking_uri: "http://127.0.0.1:8080"

data:
  input:
    path: "../data/data_processed2.csv"  # Берем результат из предыдущего этапа
    delimiter: ","
    encoding: "utf-8"
    columns:
      message_clean_no_stopwords: "message_clean_no_stopwords"
  
  output:
    path: "../data/data_without_stopwords.csv"
    save_processed: true

processing:
  extra_stopwords: [
    "движение",
    "маршрут", 
    "путь",
    "центр",
    "работать",
    "поездка",
    "подслушать"
  ]
  
  # Параметры анализа
  min_word_length: 3
  log_word_frequency: true
  create_wordcloud: true