mlflow:
  tracking_uri: "http://127.0.0.1:8080"

experiment:
  name: "topic_modeling"
  version: "v1"

data:
  input:
    path: "../data/data_processed2.csv"
    delimiter: ","
    encoding: "utf-8"
    columns: 
      message_clean_no_stopwords: "message_clean_no_stopwords"
  
vectorizer:
  max_features: 3000
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.1
  
lda:
  n_components: 7
  max_iter: 50
  learning_method: "batch"
  evaluate_every: 5
  random_state: 42
  
evaluation:
  top_words_count: 10
  coherence_metric: "c_v" 